error_messages = {"C0301": "Line is too long.",
                  "C0302": "A module has too many lines.",
                  "C0304": "The last line in a file is missing a newline.",
                  "C0305": "There is an unnecessary trailing semicolon.",
                  "C0321": "More than one statement are found on the same line (semicolon).",
                  "C0325": "Unnecessary parentheses around the keyword",
                  "C0326": "Occurs when a wrong number of spaces is used around an operator, bracket or block opener.",
                  "C0327": "Occurs when a wrong number of spaces is used around an eqality sign.",
                  "C0410": "Import statement: importing multiple modules is detected.",
                  "E0501": "Wrong encoding",
                  "A0000": "Wrong number of spaces around colon",
                  "A0001": "There is no space before function or function call or indexing",
                  "A0002": "There is a space/spaces before function or function call or indexing",
                  "A0003": "Too many spaces",
                  "A0004": "Too many spaces between name and operator",
                  "A0005": "Trailing space",
                  "A0006": "Line break after a binary operator",
                  "A0007": "Star importing",
                  "A0008": "The last line should be in the same line for one-line docstrings",
                  "A0009": "The multi-line comment should have the same indent as the surrounding code",
                  "I0001": "Wrong indent for function arguments",
                  "I0002": "Wrong indent for list arguments",
                  "S0001": "There should be at least 2 spaces before the comment line",
                  "S0002": "Exactly one space is needed between \'#\' and a comment",
                  "S0003": "Wrong indentation for multi-line comment",
                  "N0001": "Invalid name (ambiguous name)",
                  "N0002": "Non-ascii character(s) in name",
                  "N0003": "Name should be in snake-case",
                  "N0004": "Name should be in camel-case",
                  "N0005": "Name should be in upper camel-case",
                  "L0001": "Wrong amount of empty lines before the function declaration",
                  "L0002": "Wrong amoung of empty lines between class declarations"}
